### ISSUE TITLE
HW4 Discussion

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#10]
@Mosaddeq107 we can discuss our homework-related concerns and topics in the discussion section. Those topics which do not need to be an issue can be discussed over there. You can share your ideas in there.
![image](https://github.com/ubsuny/23-Homework4G1/assets/143649458/4a0b3694-9d4a-4cc8-89ff-97ac9e7320b8)

**Comment by Mosaddeq107** [comment]
Okay, good idea.

**Comment by LinxuanHu** [comment]
sure

**Comment by AhmedCode99** [comment]
ok

**Comment by Mosaddeq107** [comment]
We can close this issue. Since we are already done with this.
