### ISSUE TITLE
Workflow Run Error

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#11]
![image](https://github.com/ubsuny/23-Homework4G1/assets/143649458/09f10ffa-7ebd-40e4-8568-2328796a3686)
@laserlab are we supposed to create greetings.yml in the homework repo? 
I tried this earlier but it failed.
![image](https://github.com/ubsuny/23-Homework4G1/assets/143649458/3d2c3373-9234-433d-8da7-e33f4c04c713)
@Mosaddeq107 Do you have any idea about this?

**Comment by Mosaddeq107** [comment]
The problem is likely associated with the file directory. You might understand from the screenshot of your workflow file **_test.py_**: 
![image](https://github.com/ubsuny/23-Homework4G1/assets/66480280/eced434c-415b-413d-a050-069730750d4d)

**Comment by laserlab** [comment]
Exactly @Mosaddeq107 that is the way to trouble shoot actions. Look at their output. Also if you didn’t write it yourself, like in this case look at the actual action what it is doing.

**Comment by reshnashrestha** [comment]
Thank you @laserlab prof & @Mosaddeq107 
with these suggestions, I fixed the issues I'd been facing. And, now actions are passing.
