### ISSUE TITLE
Selection of existing Homework solution 

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#13]
Let's decide on which homework are we going to work on including the code. @LinxuanHu @Mosaddeq107

**Comment by Mosaddeq107** [comment]
We can choose any of the previous homework. I have no problem.

**Comment by reshnashrestha** [comment]
Yeah same here, but I think that it will be better to choose the one on which one of us had worked that way it will be convenient to explain to the other.

**Comment by reshnashrestha** [comment]
@LinxuanHu @Mosaddeq107 So on which hw are we working because I  believe that its better to get started by now.

**Comment by reshnashrestha** [comment]
As there is no active conversation, and it's pretty late by now, I am choosing HW3 projectile motion with air resistance. [practice_algorithm.py](https://github.com/reshnashrestha/23-Homework3G5/blob/main/practice_algorithm.py)
