### ISSUE TITLE
HW chosen!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G1#15]
We, G5, probably,  are going to choose HW2 i.e., different implementations (For Loops, NumPy Built-in Functions and , NumPy Einstein Notation Function) for matrix multiplication and dot product operations in Python for our task. What about you guys?

**Comment by reshnashrestha** [comment]
Oh that's great, we have not decided yet. We will let you know afterwards.

**Comment by tirthbha** [comment]
@reshnashrestha  Have you decided now?

**Comment by reshnashrestha** [comment]
Yes @tirthbha we are working on [projectile_motion_with_air_resistance](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_motion_with_air_resistance.py)
