### ISSUE TITLE
Steps to follow!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G1#16]
Basically, we will do the following steps for this task, if I were not wrong:
1) Initialize GitHub Actions by creating a .yml file within .github/workflows in the repository.
2) Define Workflow Triggers by specifying events like push or pull request to the main branch that initiate the workflow, which includes check out the repository, set up a Python environment, install necessary Python packages: numpy, matplotlib, pytest, flake8, perform linting using flake8, and run unit tests with pytest.
3) Finally, the Documentation part, where we will write instructions detailing the process of creating and configuring theGitHub Actions workflow.
Correct me if I was wrong here.

**Comment by reshnashrestha** [comment]
I think that you are pretty correct in here, thank you for sharing @tirthbha
