### ISSUE TITLE
Create directory

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G1#17]
Do we need to create the directory ".github/workflows/filename.yml" to the main repository or to own repository?

**Comment by reshnashrestha** [comment]
Its on own repository I think.

**Comment by tirthbha** [comment]
@reshnashrestha You mean we should merge that directory to the main later.

**Comment by laserlab** [comment]
As before. You fork the ubsuny main homework repo. Then you create inside the existing workflow folder your new action. After committing you open a PR to the original ubsuny repo

**Comment by tirthbha** [comment]
@laserlab  Thank you professor.

**Comment by reshnashrestha** [comment]
@laserlab Prof. I got it. Thank you for the clarification. 
And, much-appreciated @tirthbha
