### ISSUE TITLE
Using GitHub Action bot for commenting on issues.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework4G1#25]
Does anyone know how to use a bot for commenting on issues, if certain words are triggered?

**Comment by reshnashrestha** [comment]
I think the bot will comment for the first time only for the new user and it will not repeat for the second or more time users.
we can edit or keep the message we want to display by fixing that in the greeting.yml file.
I don't know but I tried to understand your question and hope I get it. @Pranjal-Srivastava-2023 hope this help and if not can you explain your question?
