### ISSUE TITLE
Homework Task Chosen 

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#26]
I am choosing HW3 projectile motion with air resistance. [projectile_motion_with_air_resistance.py](https://github.com/reshnashrestha/23-Homework3G5/blob/main/practice_algorithm.py)

**Comment by LinxuanHu** [comment]
which group in hw3 did it

**Comment by reshnashrestha** [comment]
It's done by G5 HW3. I renamed it here. Provided the link.
