### ISSUE TITLE
Choosing work

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework4G1#32]
Do we need to select the same work for your homework? @reshnashrestha, the work you chose, do we also need to copy the same file you have chosen?

**Comment by reshnashrestha** [comment]
@Mosaddeq107 It's like this is a group project, so I believe that working on the same previous HW is required. After meeting the requirements of group tasks, we can choose more we want to work on. Correct me if I am wrong, @laserlab

**Comment by laserlab** [comment]
The idea is to learn to work with existing code. So please choose an old homework as in the homework description,

**Comment by reshnashrestha** [comment]
@laserlab We have chosen HW3 projectile motion with air resistance. [projectile_motion_with_air_resistance.py](https://github.com/reshnashrestha/23-Homework3G5/blob/main/practice_algorithm.py)
