### ISSUE TITLE
Output for linting and pytest

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G1#35]
How could we get the output for the pytest and linting using github action?

**Comment by reshnashrestha** [comment]
@tirthbha For that in our workflow, we have to add :
    - name: Run linting
      run: pylint your_module_name

    - name: Run pytest
      run: pytest

**Comment by tirthbha** [comment]
@reshnashrestha Thank you for your reply and what will be result of linting and how could we get that?

**Comment by reshnashrestha** [comment]
It will the suggestions for you code to look better.
