### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#37]
@LinxuanHu while documenting, please include the License part as well, the file from the previous hw has an Apache license.

**Comment by reshnashrestha** [comment]
documentation: focus on the github action documentation, but also document what had to be changed, generate a list with all the items that had to be changed in the old code to adapt it to the github actions (see changelog: https://en.wikipedia.org/wiki/Changelog)

**Comment by LinxuanHu** [comment]
got it

**Comment by reshnashrestha** [comment]
@LinxuanHu documenting milestone is created.
