### ISSUE TITLE
unit testing and linting

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#38]
#unit test: focus on providing a separate function / module (based on the old code - report to documentation developer what changes are needed) to the algorithm developer, so it can be implemented as a GitHub action

**Comment by reshnashrestha** [comment]
@Mosaddeq107

**Comment by AhmedCode99** [comment]
indeed

**Comment by Mosaddeq107** [comment]
I think we are done with this.
