### ISSUE TITLE
Run code locally

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework4G1#39]
To run the code merged in the repository, you can clone it to your vs code and run locally.

**Comment by LinxuanHu** [comment]
it there any way to do it in different platform

**Comment by reshnashrestha** [comment]
Nice!
I have been using vs code. This is very nice while using command lines. For the code we are using, we need to parse the arguments in terminal. And, VS code is useful IDE.

**Comment by reshnashrestha** [comment]
As suggested in the class by professor, we can use codespace in github.
