### ISSUE TITLE
Which code did you Choose?

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework4G1#4]
Are you guys using HW 2 solution or 3?

**Comment by reshnashrestha** [comment]
@sharmistharanit we ate still discussing on that.

**Comment by tirthbha** [comment]
@sharmistharanit We chose HW2 for this task.

**Comment by reshnashrestha** [comment]
Yes @sharmistharanit  we are working on [projectile_motion_with_air_resistance](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_motion_with_air_resistance.py)
