### ISSUE TITLE
linting issue

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G1#45]
I am unable to sort out linting error using flake8 completely. There is at least one error in our case and we are unable to fix that error, which seems like : E402 module level import not at top of file. Can anyone help with this issue?
Note: I have tried  keeping the module at the top.

**Comment by reshnashrestha** [comment]
I am not sure on this. We have not done linting yet.

**Comment by reshnashrestha** [comment]
We used pylint for linting and made changes accordingly.
[pylint suggestion](https://github.com/ubsuny/23-Homework4G1/issues/46)
you can find this here.
