### ISSUE TITLE
pylint suggestion

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#46]
![image](https://github.com/ubsuny/23-Homework4G1/assets/143649458/f8f09bf0-73e6-444b-9a1e-f8d748c1bf6b)
@LinxuanHu you can include these in documentation.

**Comment by reshnashrestha** [comment]
Second time I got this: 
![image](https://github.com/ubsuny/23-Homework4G1/assets/143649458/af4e83d4-509e-4ef1-abeb-8abf4ee4190b)

you can include the steps we followed to make the ratings 10/10.

**Comment by AhmedCode99** [comment]
yes, anyone can view output of github action

**Comment by Mosaddeq107** [comment]
So, you already fixed it, right? @reshnashrestha

**Comment by LinxuanHu** [comment]
thanks, i put it in the documentation, which file did you use to do the linting

**Comment by reshnashrestha** [comment]
@LinxuanHu [linting_unittest.yml](https://github.com/ubsuny/23-Homework4G1/blob/main/.github/workflows/linting_unittest.yml) **This is yml AKA workflow file for the unit test**
and our unit test file is [projectile_unit_test.py](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_unit_test.py)
