### ISSUE TITLE
Pytest satisfied

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#48]
![image](https://github.com/ubsuny/23-Homework4G1/assets/143649458/a08ff396-1cf2-44e9-acc1-18b8532784b4)

**Comment by tirthbha** [comment]
@reshnashrestha This result seems that you have tested two examples/methods/unittest in your code, right? Could you please tell me what are the two examples you have used to do pytest in your code.

**Comment by reshnashrestha** [comment]
@tirthbha No, I did pytest for only one.

**Comment by tirthbha** [comment]
@reshnashrestha  But your pytest result shows that there are two collected items.

**Comment by reshnashrestha** [comment]
Oh maybe because I ran it twice.
Can you show that, please? @tirthbha
