### ISSUE TITLE
Making labels

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework4G1#5]
Hi @reshnashrestha 
As the maintainer, you'll need to create new labels according to the requirements.

**Comment by reshnashrestha** [comment]
Sure @Mosaddeq107 just let me know if you want something new to label.

**Comment by Mosaddeq107** [comment]
> Sure @Mosaddeq107 just let me know if you want something new to label.

Hi @reshnashrestha, you can make some new labels, namely, help wanted, fixed, bug, error, etc. Basically, you need to create more new 10 Labels for the grading purpose of our homework.

**Comment by reshnashrestha** [comment]
I have created new labels but I don't think we have to create 10 more new labels. To my understanding, we have to use 10 labels. Let's ask the clarification with prof. @laserlab

**Comment by laserlab** [comment]
Yes you need a total of ten. However it is always a good idea to discuss which to use for every new homework

**Comment by reshnashrestha** [comment]
Yes, prof, and we can create new ones as per requirements.

**Comment by laserlab** [comment]
The requirements jus say you need ten, not ten new ones

**Comment by reshnashrestha** [comment]
Yes I got it, what I mean to say here is that as per the labels required in the issues we can add that label. @laserlab prof.
