### ISSUE TITLE
check license

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework4G1#51]
Did you guys check if the license is available for your repo?

**Comment by tirthbha** [comment]
> Did you guys check if the license is available for your repo?

Could you please let me know how to check the license?

**Comment by reshnashrestha** [comment]
The code you are using belongs to HW3 of some group and it must have included License. You can look for license file in that group. 
In our case, we have used HW3G5 which has taken [Apache 2.0](https://github.com/ubsuny/23-Homework3G5/blob/main/LICENSE)

**Comment by tirthbha** [comment]
@reshnashrestha Thank you for your information.
