### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#52]
we have used hw3G5 which uses [Apache 2.0 LICENSE](https://github.com/ubsuny/23-Homework3G5/blob/9c7beaad0a99b36ca07e8eb2011abcefe082d7ee/LICENSE)

@LinxuanHu Try to cover this part as well and give credit while documenting.

**Comment by reshnashrestha** [comment]
@LinxuanHu Have you worked on this?

**Comment by AhmedCode99** [comment]
is a license required for this hw?

**Comment by Mosaddeq107** [comment]
> is a license required for this hw?

You should add, I think. Since you've added at least some codes, including writing action yml files.

**Comment by Mosaddeq107** [comment]
For more clarification, ask Dr Tim; he can answer more precisely.

**Comment by Mosaddeq107** [comment]
> is a license required for this hw?

He is working on it.

**Comment by LinxuanHu** [comment]
okay, i will add it
