### ISSUE TITLE
Elaboration

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework4G1#54]
Since I was not involved in this homework, can you (@reshnashrestha ) please explain what these variables (x0, y0, v0, and m) mean? 

https://github.com/ubsuny/23-Homework4G1/blob/df7a657e54373da39e06172dad64aa2509163ad9/projectile_motion_with_air_resistance.py#L8

**Comment by reshnashrestha** [comment]
Yeah sure @Mosaddeq107

**Comment by reshnashrestha** [comment]
x0, y0: Initial position (in meters) of the projectile (default: (0.0, 0.0)).
v0: Initial velocity (m/s) of the projectile.
Launch angle in degree and m is mass.

**Comment by AhmedCode99** [comment]
true

**Comment by Mosaddeq107** [comment]
> x0, y0: Initial position (in meters) of the projectile (default: (0.0, 0.0)). v0: Initial velocity (m/s) of the projectile. Launch angle in degree and m is mass.

Thank you for your clarification.
