### ISSUE TITLE
Accept merge request 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework4G1#56]
Hi @reshnashrestha 
Can you accept the merge request? I added the license for our homework.

**Comment by tirthbha** [comment]
@Mosaddeq107 How did you check your license that whether it is allowed or not for this task?

**Comment by reshnashrestha** [comment]
@Mosaddeq107 I viewed your file, and I believe that the copyright should be given to HW3G5 UBSUNY. Can you fix that and then pull the merge request?

**Comment by reshnashrestha** [comment]
@tirthbha You can view it in detail in the License detail section. 
for eg: [LICENSE](https://github.com/ubsuny/23-Homework3G5/blob/main/LICENSE)

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework4G1/assets/143649458/cc7e0a5d-7c58-4688-9978-704ef8445dc3)
@Mosaddeq107 I have edited your file and then merged it. Let me know if I need to fix anything here.

**Comment by Mosaddeq107** [comment]
This license preserves the right of all works for this repository. We copied some work from the previous homework of G5HW3 as their license permits that (otherwise, we couldn't use that), but we did some new work (like implementing some action workflows for lintin, unit test, documentation, etc) as well for this repository for Homework-4. Therefore, a contention might arise. Even if some new contributions are made by Group1HW4, Group5HW3 will have the complete right to this repository. Can you @reshnashrestha please look into this matter? 

> ![image](https://user-images.githubusercontent.com/143649458/275719047-cc7e0a5d-7c58-4688-9978-704ef8445dc3.png) @Mosaddeq107 I have edited your file and then merged it. Let me know if I need to fix anything here.

**Comment by reshnashrestha** [comment]
Oh, I see. I fully don't understand this. If the License needs any changes can you do that and then request a PR? @Mosaddeq107
