### ISSUE TITLE
Remaining Tasks

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#62]
@LinxuanHu and @Mosaddeq107 
Hi, I am just checking on if you have done the tasks as assigned or if you need any kind of help. Just a reminder that the due is tomorrow.

**Comment by uarif** [comment]
Can I see your documentation file? I am concern about something,. 
thank you

**Comment by Mosaddeq107** [comment]
> Can I see your documentation file? I am concern about something,. thank you

We are working on it.

**Comment by reshnashrestha** [comment]
@LinxuanHu I am also concerned about it.
