### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework4G1#70]
what do i need to include in the license

**Comment by Mosaddeq107** [comment]
Usually, you don't need to add anything to the standard licenses. However, few licenses have options to add the year, name of the owners, etc, inside the document. You can simply edit those in a license.

**Comment by Mosaddeq107** [comment]
Did you complete this part?

**Comment by reshnashrestha** [comment]
Include License means just keep in the documentation saying that we are adapting Apache 2.0 license @LinxuanHu
