### ISSUE TITLE
Created a pool request 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework4G1#74]

**Comment by Mosaddeq107** [comment]
@reshnashrestha 
I created a pool request for our code where I just added some docstrings to increase the readability. Can you please check?

**Comment by reshnashrestha** [comment]
Yeah sure.

**Comment by reshnashrestha** [comment]
@Mosaddeq107 I just checked it and is basically the same, should I merge it or what? 
@Mosaddeq107 or @LinxuanHu Who is working for documentation? 
@LinxuanHu is assigned for documentation? Can you share the part of work you are done with?

**Comment by LinxuanHu** [comment]
please check documentation.md
