### ISSUE TITLE
Documentation File Creating 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework4G1#75]

**Comment by Mosaddeq107** [comment]
HI @LinxuanHu 
Are you working on making documentation files?

**Comment by LinxuanHu** [comment]
do you know which file have linting

**Comment by LinxuanHu** [comment]
i requested to merge into the main branch, but didn't get approved yet, you can check the documentation in my fork if you want
https://github.com/LinxuanHu/23-Homework4G1/blob/main/documentation.md

**Comment by reshnashrestha** [comment]
@LinxuanHu this file is not on the pull request, Is that the final work or are you still working on?
