### ISSUE TITLE
linting

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework4G1#76]
which file is for linting

**Comment by reshnashrestha** [comment]
[projectile_unit_test.py](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_unit_test.py)

**Comment by reshnashrestha** [comment]
@LinxuanHu

**Comment by LinxuanHu** [comment]
> [projectile_unit_test.py](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_unit_test.py)

i think it's unit test, not linting

**Comment by reshnashrestha** [comment]
Linting is using this file to work on. 
under the workflow you can find linting file.

**Comment by reshnashrestha** [comment]
[linting_unittest.yml](https://github.com/ubsuny/23-Homework4G1/blob/main/.github/workflows/linting_unittest.yml)

**Comment by reshnashrestha** [comment]
https://github.com/ubsuny/23-Homework4G1/actions/runs/6536232627/job/17747467411

**This is the workflow link for linting**

**Comment by pratibha77118** [comment]
@reshnashrestha I got issues in merging because of lots of python files in the main repo. However as a maintainer we can edit and delete the older files used for testing. I am in doubts , are we allowed to do so in the main repo?

**Comment by reshnashrestha** [comment]
Well its actually not very nice to work on main repo, however I directly deleted some cache files from the main repo @pratibha77118
