### ISSUE TITLE
what does requirements.txt do

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework4G1#77]
can you explain what does requirements.txt do in this assignment

**Comment by reshnashrestha** [comment]
It fulfills the requirements to run the code like numpy, pytest, pylint, etc.

**Comment by pratibha77118** [comment]
Ya we just put the libraries that are required in our code in requirement.txt. It install and use those libraries to run the code.

**Comment by reshnashrestha** [comment]
Hope this helps @LinxuanHu
