### ISSUE TITLE
Conflicts on merging files

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework4G1#79]
Hi all,
I got this issues while merging the files. I just like to share there is resolving feature too.
<img width="1428" alt="Module file" src="https://github.com/ubsuny/23-Homework4G1/assets/72980895/2ff2b35d-43fe-4b01-b48a-65752676feed">
<img width="1147" alt="module2" src="https://github.com/ubsuny/23-Homework4G1/assets/72980895/94993bd3-77cc-45bb-a093-5e3d96d68020">

**Comment by LinxuanHu** [comment]
i think the issue is because you did not sync your branch to the latest version
