### ISSUE TITLE
New Milestone

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G1#8]
@Mosaddeq107 I have created our very first milestone stating that we target to complete this hw by October 16th.

**Comment by reshnashrestha** [comment]
We can add other milestones for GitHub actions and linting for unit-test, documentation, and algorithms. You can suggest me.  @Mosaddeq107 @LinxuanHu

**Comment by LinxuanHu** [comment]
please add a milestone for documentation

**Comment by reshnashrestha** [comment]
Sure @LinxuanHu
